//! Modular parity: assert the Rust crates reproduce, byte-for-byte, the golden
//! vectors emitted by the ORIGINAL TS implementation (iris-sdk / rose-wasm). The
//! fixture is generated by `src/parity-export.test.ts` in the original clone:
//!
//!   cd /Users/callen/work/third-party/atomic-nock-original \
//!     && npx vitest run src/parity-export.test.ts
//!
//! This is the oracle for the protocol-fragile pieces (lock root, hax hash,
//! tx-id) — see [[migration-validation-strategy]].

use serde_json::Value;
use swap_core::{encode_swap_params, hash_preimage, hash_public_key, Swap};
use swap_evm::amount::to_atomic;
use swap_evm::calls::keccak256_hex;
use swap_nock::htlc_lock_root;

fn fixture() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/parity.json");
    let raw = std::fs::read_to_string(path).unwrap_or_else(|_| {
        panic!("parity fixture missing — regenerate it from the original clone (see test header): {path}")
    });
    serde_json::from_str(&raw).expect("parity.json is valid JSON")
}

fn jam_bytes(v: &Value) -> Vec<u8> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|b| b.as_u64().unwrap() as u8)
        .collect()
}

#[test]
fn hash_preimage_matches_original() {
    let f = fixture();
    let jam = jam_bytes(&f["hashPreimage"]["jam"]);
    assert_eq!(
        hash_preimage(&jam).unwrap(),
        f["hashPreimage"]["digest"].as_str().unwrap()
    );
}

#[test]
fn hash_public_key_matches_original() {
    let f = fixture();
    assert_eq!(
        hash_public_key(&[0u8; 97]).unwrap(),
        f["hashPublicKey"]["zero97"].as_str().unwrap()
    );
    assert_eq!(
        hash_public_key(&[1u8; 97]).unwrap(),
        f["hashPublicKey"]["one97"].as_str().unwrap()
    );
}

/// The protocol-critical one: the HTLC OR-lock root our native iris-rs builder
/// produces must equal the iris-sdk lock root for identical inputs.
#[test]
fn htlc_lock_root_matches_original() {
    let f = fixture();
    let lr = &f["htlcLockRoot"];
    let got = htlc_lock_root(
        lr["hNock"].as_str().unwrap(),
        lr["buyerPkh"].as_str().unwrap(),
        lr["sellerPkh"].as_str().unwrap(),
        lr["refundHeight"].as_u64().unwrap() as u32,
    )
    .unwrap();
    assert_eq!(got.to_string(), lr["lockRoot"].as_str().unwrap());
}

#[test]
fn keccak256_matches_original() {
    let f = fixture();
    let jam = jam_bytes(&f["keccak256"]["jam"]);
    assert_eq!(keccak256_hex(&jam), f["keccak256"]["hex"].as_str().unwrap());
}

#[test]
fn to_atomic_matches_original() {
    let f = fixture();
    for case in f["toAtomic"].as_array().unwrap() {
        let got = to_atomic(
            case["amount"].as_str().unwrap(),
            case["decimals"].as_u64().unwrap() as u32,
        );
        assert_eq!(
            got.to_string(),
            case["result"].as_str().unwrap(),
            "to_atomic({}, {})",
            case["amount"],
            case["decimals"]
        );
    }
}

#[test]
fn encode_swap_params_matches_original() {
    let f = fixture();
    let lr = &f["htlcLockRoot"];
    let swap = Swap {
        h_nock: lr["hNock"].as_str().unwrap().into(),
        h_evm: "0xEvM".into(),
        seller_pkh: lr["sellerPkh"].as_str().unwrap().into(),
        buyer_pkh: lr["buyerPkh"].as_str().unwrap().into(),
        nock_refund_height: 1000,
        usdc_timelock: 5000,
        nock_gift: 65536,
        seller_eth: Some("0xSeller".into()),
        buyer_eth: Some("0xBuyer".into()),
        usdc_amount: Some("1.5".into()),
        birth_output_index: Some(2),
        nock_lock_tx_id: Some("0xnl".into()),
        ..Default::default()
    };
    assert_eq!(
        encode_swap_params(&swap),
        f["encodeSwapParams"]["json"].as_str().unwrap()
    );
}
